server:
  port: 8082

zeebe:
  client:
    cloud:
      region: bru-2
      clusterId: a5d886a1-dd23-4014-af0f-3661361924d0
      clientId: mB58ydJN1iJXoTiT2UTD-iTwyFt7zHEX
      clientSecret: llCui2c_r.nmvmbtMSVweatM0XuwR_M0naoGEmIbVoFfJ8Zb~Ahw90xvZ9a5zYy~

seller:
  mail-address: hogof14376@sfpixel.com
# You can also configure the connection to a self-managed Zeebe broker:
#    broker:
#      gateway-address: 127.0.0.1:26500
#    security:
#      plaintext: 'true'